theme = "onedark"

[editor]
scrolloff = 10
line-number = "relative"
cursorline = true
cursorcolumn = true
# rulers = [57,72,100]
# bufferline = "multiple"
end-of-line-diagnostics = "hint"

bufferline = "multiple"

[editor.soft-wrap]
enable = true

[keys.normal.space]
"n" = { "w" = ":w" } # Writes file
