[general]
import = [
  "~/.config/alacritty/themes/themes/one_dark.toml"
]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 120, lines = 36 }
padding = { x = 5, y = 5 }
dynamic_padding = true
dynamic_title = true

[font]
size = 16.0

[font.offset]
y = 0

[font.bold]
family = "Input Mono"

[font.bold_italic]
family = "Input Mono"

[font.italic]
family = "Input Mono"

[font.normal]
family = "Input Mono"

[keyboard]
bindings = [ { key = "Return", mods = "Shift", chars = "\n" } ] 
